
-- trigger para actualizar el estado del voucher una vez hecha la matricula
DROP TRIGGER IF EXISTS TGR_VOUCHER_ESTADO
DELIMITER //
CREATE TRIGGER TGR_VOUCHER_ESTADO AFTER INSERT ON TPMATRICULA
FOR EACH ROW
BEGIN
	UPDATE TMVOUCHER SET COMILLA = 1 WHERE SEC = NEW.FK_SEC_VOUCHER;
END; //