
-- trigger para actualizar el estado del voucher una vez hecha la matricula
DROP TRIGGER IF EXISTS TGR_VOUCHER_ESTADO
DELIMITER //
CREATE TRIGGER TGR_VOUCHER_ESTADO AFTER INSERT ON TPMATRICULA
FOR EACH ROW
BEGIN
	UPDATE TMVOUCHER SET COMILLA = 1 WHERE SEC = NEW.FK_SEC_VOUCHER;
END; //

-- Aula por sede unicos
DROP TRIGGER IF EXISTS TGR_AULA_SEDE_INSERT
DELIMITER //
CREATE TRIGGER TGR_AULA_SEDE_INSERT BEFORE INSERT ON TMAULA
FOR EACH ROW
BEGIN
	DECLARE V_AULASEDE VARCHAR(10);
    SET V_AULASEDE = CONCAT(NEW.NOM_AULA, NEW.FK_ID_SEDE);
    SET NEW.AULA_SEDE = V_AULASEDE;
END; //

DROP TRIGGER IF EXISTS TGR_AULA_SEDE_UPDATE
DELIMITER //
CREATE TRIGGER TGR_AULA_SEDE_UPDATE BEFORE UPDATE ON TMAULA
FOR EACH ROW
BEGIN
	DECLARE V_AULASEDE VARCHAR(10);
    SET V_AULASEDE = CONCAT(NEW.NOM_AULA, NEW.FK_ID_SEDE);
    SET NEW.AULA_SEDE = V_AULASEDE;
END; //